// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_intermediate_level_ninja = "CgkI8f7Kx4YSEAIQEA"; // <GPGSID>
        public const string achievement_scary_is_it = "CgkI8f7Kx4YSEAIQDA"; // <GPGSID>
        public const string achievement_what_an_abnormal_way_of_greeting_someone = "CgkI8f7Kx4YSEAIQGQ"; // <GPGSID>
        public const string achievement_not_very_efficient = "CgkI8f7Kx4YSEAIQEg"; // <GPGSID>
        public const string achievement_lemon_squeezy = "CgkI8f7Kx4YSEAIQCQ"; // <GPGSID>
        public const string achievement_master_ninja = "CgkI8f7Kx4YSEAIQFg"; // <GPGSID>
        public const string achievement_advanced_level_ninja = "CgkI8f7Kx4YSEAIQFA"; // <GPGSID>
        public const string achievement_terratfic = "CgkI8f7Kx4YSEAIQEQ"; // <GPGSID>
        public const string achievement_novice_ninja = "CgkI8f7Kx4YSEAIQDg"; // <GPGSID>
        public const string achievement_the_normal_way_to_leave = "CgkI8f7Kx4YSEAIQBA"; // <GPGSID>
        public const string achievement_pretty_standard = "CgkI8f7Kx4YSEAIQBQ"; // <GPGSID>
        public const string achievement_the_one_who_beat_impossible = "CgkI8f7Kx4YSEAIQBw"; // <GPGSID>
        public const string achievement_easy_peasy = "CgkI8f7Kx4YSEAIQAg"; // <GPGSID>
        public const string achievement_ahead_of_the_curve = "CgkI8f7Kx4YSEAIQEw"; // <GPGSID>
        public const string achievement_now_its_getting_serious = "CgkI8f7Kx4YSEAIQBg"; // <GPGSID>
        public const string achievement_amateur_ninja = "CgkI8f7Kx4YSEAIQDw"; // <GPGSID>
        public const string achievement_this_must_be_on_purpose = "CgkI8f7Kx4YSEAIQGg"; // <GPGSID>
        public const string achievement_still_not_hard_enough = "CgkI8f7Kx4YSEAIQCg"; // <GPGSID>
        public const string achievement_survivor = "CgkI8f7Kx4YSEAIQDQ"; // <GPGSID>
        public const string achievement_welcome_to_the_maze = "CgkI8f7Kx4YSEAIQAQ"; // <GPGSID>
        public const string achievement_the_top_5 = "CgkI8f7Kx4YSEAIQCA"; // <GPGSID>
        public const string achievement_a_walk_in_the_park = "CgkI8f7Kx4YSEAIQCw"; // <GPGSID>
        public const string achievement_unnecessary_medication = "CgkI8f7Kx4YSEAIQFQ"; // <GPGSID>
        public const string achievement_the_top_1 = "CgkI8f7Kx4YSEAIQHA"; // <GPGSID>
        public const string achievement_thats_not_very_nice = "CgkI8f7Kx4YSEAIQGA"; // <GPGSID>
        public const string achievement_deep_rooted_hate = "CgkI8f7Kx4YSEAIQFw"; // <GPGSID>

}

